openapi: 3.0.0
info:
  title: "Podcasts REST API"
  description: "An API about ultimate podcasts"
  version: "1.0.0"

servers:
  - url: "/api"

paths:
  /podcasts:
    get:
      operationId: "podcasts.read_all"
      tags:
        - "Podcasts"
      summary: "Read the list of podcasts"
      responses:
        "200":
          description: "Successfully read podcast list"
    post:
      operationId: "podcasts.create"
      tags:
        - Podcasts
      summary: "Create a podcast"
      requestBody:
        description: "Podcast to create"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "podcast"
              $ref: "#/components/schemas/Podcast"
      responses:
        "201":
          description: "Successfully created podcast"
        "400":
          description: "Invalid request"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not found"

  /podcasts/{title}:
    get:
      operationId: "podcasts.search"
      tags:
        - Podcasts
      summary: "Read one podcast"
      parameters:
        - $ref: "#/components/parameters/title"
      responses:
        "200":
          description: "Successfully read podcast"
        "400":
          description: "Invalid request"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not found"
    put:
      tags:
        - Podcasts
      operationId: "podcasts.update"
      summary: "Update a podcast"
      parameters:
        - $ref: "#/components/parameters/title"
      responses:
        "200":
          description: "Successfully updated podcast"
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: "podcast"
              $ref: "#/components/schemas/Podcast"
    delete:
      tags:
        - Podcasts
      operationId: "podcasts.delete"
      summary: "Delete a podcast"
      parameters:
        - $ref: "#/components/parameters/title"
      responses:
        "204":
          description: "Successfully deleted podcast"

components:
  schemas:
    Podcast:
      type: "object"
      required:
        - title
        - publisher
        - genre
        - release_date
      properties:
        title:
          type: "string"
        publisher:
          type: "string"
        genre:
          type: "string"
        release_date:
          type: "string"
          format: "date"
  parameters:
    title:
      name: "title"
      description: "Title of the podcast"
      in: path
      required: True
      schema:
        type: "string"
